# Generated by Django 4.1.5 on 2023-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0016_auto_20210820_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office_staff",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
                ("Sex", models.CharField(max_length=50)),
                ("DOB", models.DateField()),
                ("Skills", models.CharField(max_length=100)),
                (
                    "Designation",
                    models.CharField(
                        choices=[
                            ("Office Assistant Jobs", "Office Assistant Jobs"),
                            ("Admin Executive Jobs", "Admin Executive Jobs"),
                            ("Receptionist Jobs", "Receptionist Jobs"),
                            (
                                "Customer Care Executive Jobs",
                                "Customer Care Executive Jobs",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
