# Generated by Django 4.1.5 on 2023-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0019_alter_office_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="ID",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
