# Generated by Django 4.1.5 on 2023-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0020_alter_office_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="office_staff",
            name="Sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=50
            ),
        ),
    ]
