# Generated by Django 4.1.5 on 2023-01-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0021_alter_office_staff_id_alter_office_staff_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="Skills",
            field=models.CharField(
                choices=[
                    ("Office Assistant Jobs", "Office Assistant Jobs"),
                    ("Admin Executive Jobs", "Admin Executive Jobs"),
                    ("Receptionist Jobs", "Receptionist Jobs"),
                    ("Customer Care Executive Jobs", "Customer Care Executive Jobs"),
                ],
                max_length=100,
            ),
        ),
    ]
