# Generated by Django 4.1.5 on 2023-01-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0022_alter_office_staff_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="Skills",
            field=models.CharField(
                choices=[
                    (
                        "Critical thinking and problem solving",
                        "Critical thinking and problem solving",
                    ),
                    ("Teamwork and collaboration", "Teamwork and collaboration"),
                    (
                        "Professionalism and strong work ethic",
                        "Professionalism and strong work ethic",
                    ),
                    (
                        "Oral and written communications skills",
                        "Oral and written communications skills",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
