# Generated by Django 4.1.5 on 2023-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0025_alter_office_staff_sex_alter_student_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="Sex",
            field=models.CharField(choices=[(0, "Male"), (1, "Female")], max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[(0, "Male"), (1, "Female")], default="Male", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[(0, "Male"), (1, "Female")], default="Male", max_length=50
            ),
        ),
    ]
