# Generated by Django 4.1.5 on 2023-01-10 16:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0027_alter_office_staff_sex_alter_student_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="Skills",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (
                        "Critical thinking and problem solving",
                        "Critical thinking and problem solving",
                    ),
                    ("Teamwork and collaboration", "Teamwork and collaboration"),
                    (
                        "Professionalism and strong work ethic",
                        "Professionalism and strong work ethic",
                    ),
                    (
                        "Oral and written communications skills",
                        "Oral and written communications skills",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
