# Generated by Django 4.1.5 on 2023-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0028_alter_office_staff_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office_staff",
            name="Sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=50,
            ),
        ),
    ]
